# docker-compose.dev.yml
# This is the docker-compose.dev.yml use for develop a project with python 3.8, Django and Postgresql

version: "3.7"

services:
  web:
    restart: unless-stopped
    container_name: django_pizzarest
    build: 
      context: .
      dockerfile: Dockerfile.dev

    networks: 
      test_net:
        ipv4_address: 172.26.1.1
  
    command:
      sleep infinity
      # python manage.py runserver
      #  0.0.0.0:8000

    volumes:
      - ./app:/djangopizzarest
      # - static_volume:/djangopizzarest/web/staticfiles
      # - media_volume:/djangopizzarest/web/mediafiles

    # ports:
      # - 8000:8000


    env_file: 
      - ./.env.dev

    depends_on:
      - db

  db:
    restart: unless-stopped
    container_name: postgres_db_pizzarest
    image: postgres:12-alpine
    
    # ports:
    #   - 5432:5432

    networks: 
      test_net:
        ipv4_address: 172.26.1.2

    volumes:
      - postgres-data:/var/lib/postgresql/data


    environment: 
      - POSTGRES_DB=hello_django_dev
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=supersecretpassword


volumes:
    postgres-data:
    # static_volume:
    # media_volume:

networks: 
  test_net:
    ipam: 
      driver: default
      config: 
        - subnet: 172.26.1.0/16

